In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("NBData.csv")
data

Outlook  Temp Humidity    Windy Play
0      Sunny   Hot     High  No wind  Yes
1      Sunny   Hot     High    Windy  Yes
2   Overcast   Hot     High  No wind   No
3      Rainy  Mild     High  No wind  Yes
4      Rainy  Cool   Normal  No wind   No
5      Rainy  Cool   Normal    Windy   No
6   Overcast  Cool   Normal    Windy  Yes
7      Sunny  Mild     High  No wind   No
8      Sunny  Cool   Normal  No wind   No
9      Rainy  Mild   Normal  No wind  Yes
10     Sunny  Mild   Normal    Windy   No
11  Overcast  Mild     High    Windy  Yes
12  Overcast   Hot   Normal  No wind  Yes
13     Rainy  Mild     High    Windy  Yes

In [13]:
myencoder = OrdinalEncoder()
myencoder = myencoder.fit(data)
myencoder.categories_

[array(['Overcast', 'Rainy', 'Sunny'], dtype=object),
 array(['Cool', 'Hot', 'Mild'], dtype=object),
 array(['High', 'Normal'], dtype=object),
 array(['No wind', 'Windy'], dtype=object),
 array(['No', 'Yes'], dtype=object)]

In [14]:
# Control
myencoder.inverse_transform([[0, 0, 0, 0, 0],
                           [1, 1, 1, 1, 1]])

array([['Overcast', 'Cool', 'High', 'No wind', 'No'],
       ['Rainy', 'Hot', 'Normal', 'Windy', 'Yes']], dtype=object)

In [15]:
# Create encoded data set
encodedData = myencoder.fit_transform(data)
encodedData

array([[2., 1., 0., 0., 1.],
       [2., 1., 0., 1., 1.],
       [0., 1., 0., 0., 0.],
       [1., 2., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 1., 1., 0.],
       [0., 0., 1., 1., 1.],
       [2., 2., 0., 0., 0.],
       [2., 0., 1., 0., 0.],
       [1., 2., 1., 0., 1.],
       [2., 2., 1., 1., 0.],
       [0., 2., 0., 1., 1.],
       [0., 1., 1., 0., 1.],
       [1., 2., 0., 1., 1.]])

In [30]:
# Import Naive Bayes Model
from sklearn.naive_bayes import GaussianNB
# split Xs(features) and Y(response)
X = encodedData[:,[0,1,2,3]]
Y = encodedData[:, [4]].ravel()

# Run the model
model = GaussianNB()
model.fit(X, Y) # X:input feature  Y:response feature

GaussianNB()

In [31]:
# Predict New Data
predicted = model.predict([[1, 2, 1, 0]]) # [Rainy, Mild, Normal, Nowind]
predicted

array([1.])

In [43]:
# Training Performance
predicted = model.predict(X)
print("Actual:          " ,Y)
print("Predicted:       ", predicted)
print("Abs(predicted-Y):", abs(predicted-Y)) # 4 out of 14 predict gave incorrect results

Actual:           [1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1.]
Predicted:        [1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1.]
Abs(predicted-Y): [0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0.]


In [44]:
from sklearn.metrics import accuracy_score
training_acc_score = accuracy_score(Y, predicted)
print(training_acc_score)

0.7142857142857143


In [45]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(predicted, Y)
print(conf_mat)

[[3 1]
 [3 7]]
