In [ ]:
#                                          NUMPY PAKETİ

In [ ]:
# Numpy Paketi listelerde matematiksel işlem yapabilmek için geliştirildi. Numpy dizilerinin normal listelerden 
# farkı listeler farklı tür veriler içerebilirken Numpy dizileri tek türde veri içerir.

In [ ]:
# !! Herhangi bir Python listesini .array() metodunu kullanıp Numpy(Numeric Python) dizisine dönüştürebiliriz.
#  numpy_list = np.array([my_list])

In [1]:
list0 = [2, 12, 4]
list1 = [4, 6, 5]
print(list0 + list1)
# Numpy dizilerinde ise bu işlemi eleman bazında toplayarak yapar.

[2, 12, 4, 4, 6, 5]


In [ ]:
# İndeks noya göre seçme listeler ile aynı.
# Ör// np_list[0]

In [2]:

!pip install numpy
!pip install pandas


     |████████████████████████████████| 14.5 MB 132 kB/s eta 0:00:01
You should consider upgrading via the '/home/hasan/code/jupyterenvironment/bin/python -m pip install --upgrade pip' command.
     |████████████████████████████████| 9.3 MB 2.1 MB/s eta 0:00:01
     |████████████████████████████████| 509 kB 2.6 MB/s eta 0:00:01
You should consider upgrading via the '/home/hasan/code/jupyterenvironment/bin/python -m pip install --upgrade pip' command.


In [3]:
import numpy as np
my_list = [12, 4, 6]
my_list_np = np.array(my_list)
print(type(my_list_np))

<class 'numpy.ndarray'>


In [8]:
# Numpy modülünde sayı dizileri oluşturmak için;
# *arange * linspace *logspace
np.arange(1, 10)
np.arange(1, 10, 2)
np.linspace(-2, 2, 21) # -2 ile 2 arasında 21 eşit aralıklı sayı
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

In [24]:
import numpy as np
exam1 = [100, 90, 45, 80]
exam2 = [70, 60, 85, 40]
exam1_np = np.array(exam1)
exam2_np = np.array(exam2)
average = (exam1_np + exam2_np)/2
print(average)

[85. 75. 65. 60.]


In [25]:
exam1_np[2] # Listelerdeki gibi.

45

In [26]:
average < 70

array([False, False,  True,  True])

In [27]:
average[average<70]

array([65., 60.])

In [29]:
# Numpy dizileri aslında n-boyutlu diziler olarak tanımlanmıştır. Bir Numpy dizisinin türünü type() fonksiyonu ile
# görmek istediğimizde numpy.ndarray olduğunu görürüz. Bu ifadedeki ndarray ifadesi n dimensional array yani n 
# boyutlu dizi anlamına gelir.
type(exam1_np)

numpy.ndarray

In [4]:
# ÇOK BOYUTLU NUMPY DİZİLERİ
price  = np.array([[45, 56, 85],
                  [26, 30, 12],
                  [77, 75, 54]])
print(price)


NameError: name 'np' is not defined

In [35]:
numbers = np.arange(20)
print(numbers)
numbers[:7]
numbers[::3]
# Listelerdeki gibi dizi[başlangıç: bitiş: adım]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([ 0,  3,  6,  9, 12, 15, 18])

In [38]:
# !! 2 veya daha yüksek boyutlu dizilerde aynı kuralı, her boyut için yazdığımız endekslerin arasına virgül koyarak
# belirtiriz.
matris = numbers.reshape(4, 5)
matris


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
matris[2:3, 3:4] # 2.satır 3. sütundaki eleman (0 dan başladığını unutma!)

array([[13]])

In [8]:
# Bir Numpy dizisinin farklı eksenleri(yükseklik, satır veya sütun) üzerindeki toplamları bulmak için
# .sum() metodu kulllanılır.
# !! 2 Boyutlu dizilerde sütun 0, satır 1 indeksi ile gösterilir.
# !! 3 Boyutlu dizilerde yükseklik 0, sütun 1, satır 0 ile gösterilir.
# 3 Boyutlu bir dizi oluşuralım.
import numpy as np
dizi = np.array([[[2, 3, 4, 5],
                [6, 7, 8, 9],
                [10, 11, 12, 13]],
                [[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]]])
print(dizi)


[[[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [9]:
dizi.sum(0) # Yükseklik Toplamı

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25]])

In [10]:
dizi.sum(1)

array([[18, 21, 24, 27],
       [15, 18, 21, 24]])

In [11]:
dizi.sum(2)

array([[14, 30, 46],
       [10, 26, 42]])

In [ ]:
# Not// Kaç Boyutlu Olursa OLsun Numpy Dizisi Mutlaka Aynı Türdeki Verilerden OLuşur.

In [16]:
# Birikimli toplamak için cumsum() metodu kullanılır.


In [ ]:
# Numpy Dizilerinde Kullanılan Diğer Metodlar:
# dizi.max() [Verilen eksendeki max değerler]  dizi.argmax() [Verilen eksendeki max değerlerin sıra nosu]
# dizi.min()   dizi.ptp() [Verilen eksendeki min ve max değerler arasındaki fark] dizi.round(a) [Dizide yer alan
# a ondalık basamağa kadar yuvarlar.] # dizi.trace() [Dizideki köşegenlerin toplamını hesaplar.]
# dizi.mean() [Verilen eksen boyunca ortalama değerleri hesaplar.] dizi.var() [Verilen eksen boyunca varyans hesaplar]
# dizi.std() [Verilen eksen boyunca standart sapmaları hesaplar. dizi.prod() [Verilen eksendeki sayıların çarpımını hesaplar]
# dizi.sort() Verilen eksendeki verilerin sıralanmış halini iletir.

In [21]:
hisse_fiyat = np.array([[2, 4, 8],
               [5, 12, 47],
               [21, 25, 82]])
hisse_fiyat[1]
hisse_fiyat[1][2]
hisse_fiyat[0:1][0:2]

array([[2, 4, 8]])

In [25]:
# Numpy dizilerinde aritmatik işlemlerde yapmak mümkün.
a = np.array([[2, 4, 8],
               [5, 12, 47],
               [21, 25, 82]])
b = np.array([[1, 5, 8],
               [4, 16, 22],
               [1, 3, 5]])

a + b 
a - b
a / b
a * b

array([[   2,   20,   64],
       [  20,  192, 1034],
       [  21,   75,  410]])

In [26]:
# 2 numpy dizisi arasında matris çarpımı yapmak için; np.matmul()
np.matmul(a, b)

array([[  26,   98,  144],
       [ 100,  358,  539],
       [ 203,  751, 1128]])

In [ ]:
# Numpy metodlarını uygyulama yöntemleri:
# 1) dizi.(metod ismi)
# 2) np.metodismi(dizi)

In [28]:
np.sum(a[:1])
np.mean(a[:,2])

45.666666666666664

In [32]:
import numpy as np
hisse_fiyat = np.array([[2, 4, 8],
               [5, 12, 47],
               [21, 25, 82]])
print(hisse_fiyat)
# 2 Boyutlu dizimize for döngüsü uygularsam şöyle bir sonuç alırım.
for i in hisse_fiyat:
    print(i)
# Döngüyü doğrudan doğruya Numpy dizisine uyguladığında dizi içerisindeki listeleri görürsün ya da diğer bir 
# deyişle satırları görürsün.

[[ 2  4  8]
 [ 5 12 47]
 [21 25 82]]
[2 4 8]
[ 5 12 47]
[21 25 82]


In [33]:
# Peki ben tek tek dizinin elemanlarına bakmak istiyorum: .nditer()
for i in np.nditer(hisse_fiyat):
    print(i)


2
4
8
5
12
47
21
25
82


In [ ]:
#                                Kullanışlı Numpy Metodları

In [36]:
np.amax(hisse_fiyat, axis=0) # İstenen eksendeki max değeri verir.amin() tam tersini verir.

array([21, 25, 82])

In [ ]:
# np.concatenate() : 2 Numpy dizisini istenen eksenlerden birleştirmek için kullanılır.
# Örneğin 2 boyutlu 2 diziyi birleştirmek için axis = 0  olursa satırları yani alt alta,
# x = 1 olursa sütunları yani yan yana birleştirir.

In [38]:
c = np.arange(1, 7).reshape(3, 2)
d = np.arange(7, 13) .reshape(3, 2)
c
d

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [40]:
np.concatenate([c ,d], axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [41]:
np.concatenate([c, d], axis= 1)

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [42]:
# np.intersect1d() : 2 veya daha fazla Numpy dizisindeki ortak elemanları seçer.
z = np.array([2, 12, 7, 9])
l = np.array([12, 7, 10])
np.intersect1d(z, l)

array([ 7, 12])

In [43]:
# np.isin() aranan elemanların dizide veya listede olup olmağını gösterir.
np.isin(l, z)


array([ True,  True, False])

In [47]:
# np.isnan() Bir dizideki verilerin NaN(Not a Number) olup olmadığını görmek için.
e = np.log([3, 4, -2])

np.isnan(e)


<ipython-input-47-59d6115ecc05>:2: RuntimeWarning: invalid value encountered in log
  e = np.log([3, 4, -2])


array([False, False,  True])

In [48]:
# np.ones() Birlerden meydana gelen istenen boyutta bir Numpy dizisi oluşturur.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
# np.repeat() Tekrarlanan elemanlardan meydana gelen bir dizi oluşturur.
np.repeat(3, 6)

array([3, 3, 3, 3, 3, 3])

In [51]:
# np.setdiff1d() Bir dizide olup  diğerinde olmayan elemanları seçmek için kullanılır.
z = np.array([2, 12, 7, 9])
l = np.array([12, 7, 10])
np.setdiff1d(z, l)

array([2, 9])

In [52]:
# np.unique() Bir dizideki tekil değerleri gösterir.
un = np.array([2, 2, 12, 5, 5])
np.unique(un)

array([ 2,  5, 12])

In [55]:
# np.where() Bir Numpy dizisinde istenen şartları sağlayan elemanları seçmek için kullanılır.
sartlı_dizi = np.arange(0, 101)
np.where(sartlı_dizi % 10 == 0)


(array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]),)

In [59]:
# np.zeros Sıfırdan meydana gelen istenen boyutta Numpy Dizisi oluşturur.
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])